### ISSUE TITLE
Data loss prevention makes requests on every iteration of loop

### ISSUE THREAD

**Issue by jaortiz117** [UPRM-Moonbuggy-Telemetry/OnBoard-Scripts#1]
During for loop you are making a request posting entire array. I think it would be more efficient making the request only at the end of loop, thereby posting the entire array all at once (its more efficient to access DB only once as opposed to many times)

**Comment by UPRMMoonBuggy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Why requests on every iteration? (py scripts)](https://trello.com/c/bUTDBEB1/48-why-requests-on-every-iteration-py-scripts)
